### ISSUE TITLE
Define DICOM tag operations for MS-PINPOINT

### ISSUE THREAD

**Issue by stefpiatek** [UCLH-Foundry/PIXL#284]
### Definition of Done / Acceptance Criteria

- [x] We will have a list of the required DICOM tags required to export the data and convert it to NIfTI format
- [x] We will investigate whether different MR machines require different tags
  - [x] query VNA for all accession numbers to get scanner tag to see how many there are
- [x] We will define what tag operations are required for the tags and match the format currently in pixl

### Documentation

- [ ] add documentation to the rolling skeleton for investigation of tags, scripts that aid this and any other information so that we can make this a business as usual process

### Dependencies

[Remote desktop and connection to GAE documentation](https://uclh.slab.com/posts/uclh-remote-environment-access-set-up-5nmpt0u1)

- [x] Access to data science desktop, windows 10 remote desktop as a backup (Rich Clarke) 
- [x] Access to GAE05 (send ssh key to Dave Ramlakhan)

### Details and Comments

Expect the easiest first approach is to:

- Create input from Arman's list of accession numbers and MRNs that matches OMOP parquet structure
- Run a dedicated instance of pixl that doesn't export outside of UCLH in `pixl_test` on GAE05 using this as an input
- Attach a shell prompt to the `orthanc-raw` container and use this as a staging area to remove tags and test conversion

Plan of work:

- [x] use junaids export to find difficult studies
- [x] use cohort with default anonymisation using dicom2niix private tags
- [x] run pipeline through with this config and then copy onto windows 
- [x] test with nifti conversion

**Comment by ruaridhg** [comment]
- @ruaridhg looking into creating a new populate function in `cli` for imaging data only i.e. get messages in same form as `messages = messages_from_parquet(parquet_dir, project_name, omop_es_datetime)` since we only have mrn, accession number, datetime etc.
- Set `ORTHANC_AUTOROUTE_RAW_TO_ANON=false` as we just want to query the VNA and not anonymise at this stage
- @jstutters add functionality into `orthanc-raw` to query vna for scanner tag and store in csv (would it be useful in future to add scanner tag to the PIXL db?)

**Comment by ruaridhg** [comment]
Had issues with permissions on GAE which @stefpiatek will look into. Could activate conda environment, but couldn't update dependencies

**Comment by skeating** [comment]
Arman agreed this could be closed
