### ISSUE TITLE
Allow DICOM tag operations to be customised per MR model

### ISSUE THREAD

**Issue by stefpiatek** [UCLH-Foundry/PIXL#292]
### Definition of Done / Acceptance Criteria

priority may change based on investigations of MR machines used and their tags.

- [x] Validate and parse a configuration file per project. This has a way to define overrides for the default operations based on values of sepcific dicom tags 
  - [ ] Will be able to define a default action if none of the pre-defined values match the value in the current DICOM study. Would be good to have `do nothing` (so no overriding takes place) or `throw exception` (only known values are allowed)

### Testing

- [ ] module-level tests for overriding, doing nothing and throwing an exception

### Documentation

- [x] Update the documentation in orthanc anon

### Dependencies

- [x] #232 
- [ ] #291 

### Details and Comments

- Will need to be regex to match, 
- [ ] @stefpiatek to output list of options of manufacturer

**Comment by stefpiatek** [comment]
DICOM tags to get the make and model:

Manufacturer (0008,0070)
ManufacturerModelName (0008,1090)

**Comment by jstutters** [comment]
I wouldn't expect too much variation at the model level so ideally we'll be able to define operations at the manufacturer level then override those as necessary for models with different behaviour.

**Comment by milanmlft** [comment]
### Plan

- [ ] Adapt `pytest_pixl.generate_dicom_dataset()` to add manufacturer tag(s) to test data
- [ ] Update `pixl_dcmd.merge_tag_schemes()` so it can actually merge multiple tag schemas
	- [ ] Should only be done if the dataset has the corresponding manufacturer tag!
- [ ] Create mock manufacturer-specific schema for testing, in `projects/configs/tag-operations/<manufacturer>.yaml`
- [ ] Decide what to do when a tag is specified in the schema, but is not present in the DICOM dataset

**Comment by milanmlft** [comment]
Updating `pixl_dcmd.merge_tag_schemes()` to handle multiple tag schemes turns out to be a bit challenging. Because a single tag scheme read from a YAML file is a `list[dict]`, where `dict` has keys `['name', 'group', 'element', 'op']`. To merge two schemes, we would need to combine the two `list[dict]`s without duplicating some tags, which is tricky because there's no way to uniquely identify elements in a list, without checking the element itself.
One possible solution would be to convert the `list[dict]` to a `dict[dict]` and use the combination of `group` and `element`, which presumably are unique for each tag,  as the keys for the new `dict`.
