### ISSUE TITLE
Store project name in DICOM tags

### ISSUE THREAD

**Issue by stefpiatek** [UCLH-Foundry/PIXL#296]
### Definition of Done / Acceptance Criteria

- To enable routing of images to the correct study, use private DICOM tag to store:
  - [ ] project name (long string) 
  - Makes sense to do this from imaging-api after we've queried the VNA for the image (and if the image already exists in orthanc raw)
- [ ] In Orthanc anon. Use the project name to query for the `Export` row in pixl pipeline db, and then use that to find the `Image` that matches the DICOM data and the `Export` entity

### Details and Comments

- project name is in the Message that `imaging-api` gets, and we should add it to the DICOM if the `Study exists in cache` or at the end of the `process_message` function in the imaging api's `_processing.py` file
- As a quick starter for ten, let's use the current tag for breed description because I think we're unlikely to want to keep that as it seems to be for non-humans. [(0010,2292)	LO	Patient Breed Description](https://www.dicomlibrary.com/dicom/dicom-tags/) 
- [Modification of a single instance](https://orthanc.uclouvain.be/book/users/anonymization.html#modification-of-a-single-instance) From anonymisation work you can supply the specific group and element tag so I think sending a rest request via the API like this should work
```
"Replace": {
              "0010-2292": "project-name"
            },
```

**Comment by jstutters** [comment]
Rules for private tags are described here: https://dicom.nema.org/dicom/2013/output/chtml/part05/sect_7.8.html
pydicom should be able to do most of the fiddly bits of adding new private tags: https://pydicom.github.io/pydicom/stable/old/private_data_elements.html#introduction

**Comment by jstutters** [comment]
Plan is to:
 - [ ] allow the orthanc-raw REST API endpoint to receive the project name
 - [ ] add the project name to the request made from imaging-api to orthanc-raw which triggers the pull from the VNA.
 - [ ] write the project name in to the DICOM metadata using a library that will do the heavy lifting with the tags for us
   - [ ] if private tags turn out to be a nightmare fallback to 'Patient Breed'
 - [ ] modify orthanc-anon so that it will pass our tag containing the project name

Not going to worry about multiple projects running simultaneously requiring the same DICOM instance but might need to add project information to the error that will be raised if an image doesn't reach the final endpoint.
